# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denker', '0005_auto_20170403_1329'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.TextField(blank=True, max_length=250, null=True, unique=True)),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('sprache', models.TextField()),
                ('autor', models.TextField()),
                ('link', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'framework_artikel',
            },
        ),
        migrations.CreateModel(
            name='Buecher',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('sprache', models.TextField()),
                ('autor', models.TextField()),
                ('link', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'framework_buecher',
            },
        ),
        migrations.CreateModel(
            name='Dokumente',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('text_de', models.TextField()),
                ('text_eng', models.TextField()),
                ('img', models.TextField()),
                ('denker', models.TextField()),
                ('orte', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'framework_dokumente',
            },
        ),
        migrations.CreateModel(
            name='Ereignisse',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('ereignis', models.TextField()),
                ('jahr', models.IntegerField()),
                ('denker', models.TextField()),
                ('text_de', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'framework_ereignisse',
            },
        ),
        migrations.CreateModel(
            name='Orte',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('name', models.TextField()),
                ('img', models.TextField()),
                ('text', models.TextField()),
                ('text_en', models.TextField()),
                ('lat', models.TextField()),
                ('lng', models.TextField()),
                ('denker', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'framework_orte',
            },
        ),
        migrations.CreateModel(
            name='Projekte',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.TextField()),
                ('autor', models.TextField()),
                ('autor_id', models.TextField()),
                ('beschreibung', models.TextField()),
                ('spenden', models.IntegerField()),
                ('ziel', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'framework_projekte',
            },
        ),
        migrations.CreateModel(
            name='StatischeInhalte',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('info', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'framework_statische_inhalte',
            },
        ),
        migrations.CreateModel(
            name='Verlagsprogramm',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('author', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'framework_verlagsprogramm',
            },
        ),
        migrations.CreateModel(
            name='Zitate',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('autor', models.TextField()),
                ('text', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'framework_zitate',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
