# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20170403_1335'),
    ]

    database_operations = [
        migrations.AlterModelTable('Buecher', 'literatur_buecher'),
        migrations.AlterModelTable('Artikel', 'literatur_artikel'),
        migrations.AlterModelTable('Dokumente', 'literatur_dokumente'),
    ]

    state_operations = [
        migrations.DeleteModel('Buecher'),
        migrations.DeleteModel('Artikel'),
        migrations.DeleteModel('Dokumente'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
