# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0003_auto_20170410_1721'),
    ]

    database_operations = [
        migrations.AlterModelTable('Orte', 'orte_orte')
    ]

    state_operations = [
        migrations.DeleteModel('Orte')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
