# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0005_auto_20170425_0808'),
    ]

    database_operations = [
        migrations.AlterModelTable('Projekte', 'projekte_projekte')
    ]

    state_operations = [
        migrations.DeleteModel('Projekte')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
