# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denker', '0010_auto_20170414_1518'),
        ('verlag', '0002_auto_20170425_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='verlagsprogramm',
            name='denker',
            field=models.ManyToManyField(to='denker.Denker'),
        ),
    ]
