# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verlag', '0003_verlagsprogramm_denker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verlagsprogramm',
            name='denker',
            field=models.ManyToManyField(blank=True, null=True, to='denker.Denker'),
        ),
    ]
