# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projekte',
            table='projekte',
        ),
    ]
