# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0010_auto_20170713_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='spenden',
            name='Datum',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
