# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0011_spenden_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spenden',
            name='Datum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
