# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0012_auto_20170713_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stufen',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekte.Projekte'),
        ),
    ]
