# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('sprache', models.TextField()),
                ('autor', models.TextField()),
                ('link', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'db_table': 'artikel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Artikelalt',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('sprache', models.TextField()),
                ('autor', models.TextField()),
                ('link', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'db_table': 'artikelalt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Buecher',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('sprache', models.TextField()),
                ('autor', models.TextField()),
                ('link', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'db_table': 'buecher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Buecheralt',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('sprache', models.TextField()),
                ('autor', models.TextField()),
                ('link', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'db_table': 'buecheralt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Denker',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('name', models.TextField()),
                ('img', models.TextField()),
                ('bio', models.TextField()),
                ('bio_en', models.TextField()),
                ('geburt', models.DateField()),
                ('tod', models.DateField()),
                ('gen', models.IntegerField()),
            ],
            options={
                'db_table': 'denker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DenkerAlt',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('name', models.TextField()),
                ('img', models.TextField()),
                ('bio', models.TextField()),
                ('bio_en', models.TextField()),
                ('geburt', models.DateField()),
                ('tod', models.DateField()),
            ],
            options={
                'db_table': 'denker_alt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dokumente',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('text_de', models.TextField()),
                ('text_eng', models.TextField()),
                ('img', models.TextField()),
                ('denker', models.TextField()),
                ('orte', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'db_table': 'dokumente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ereignisse',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('ereignis', models.TextField()),
                ('jahr', models.IntegerField()),
                ('denker', models.TextField()),
                ('text_de', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'db_table': 'ereignisse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orte',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('name', models.TextField()),
                ('img', models.TextField()),
                ('text', models.TextField()),
                ('text_en', models.TextField()),
                ('lat', models.TextField()),
                ('lng', models.TextField()),
                ('denker', models.TextField()),
            ],
            options={
                'db_table': 'orte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ortebackup',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('name', models.TextField()),
                ('img', models.TextField()),
                ('text', models.TextField()),
                ('text_en', models.TextField()),
                ('lat', models.TextField()),
                ('lng', models.TextField()),
                ('denker', models.TextField()),
            ],
            options={
                'db_table': 'ortebackup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projekte',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.TextField()),
                ('autor', models.TextField()),
                ('autor_id', models.TextField()),
                ('beschreibung', models.TextField()),
                ('spenden', models.IntegerField()),
                ('ziel', models.IntegerField()),
            ],
            options={
                'db_table': 'projekte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatischeInhalte',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'statische_inhalte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Verlagsprogramm',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('author', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'db_table': 'verlagsprogramm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zitate',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('autor', models.TextField()),
                ('text', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'db_table': 'zitate',
                'managed': True,
            },
        ),
    ]
