# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denker', '0002_auto_20170331_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artikelalt',
        ),
    ]
