# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denker', '0005_auto_20170403_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denker',
            old_name='id',
            new_name='slug',
        ),
    ]
