# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denker', '0007_auto_20170403_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denker',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
