# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denker', '0008_auto_20170403_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denker',
            options={'managed': True, 'verbose_name': 'Denker', 'verbose_name_plural': 'Denker'},
        ),
        migrations.AlterField(
            model_name='denker',
            name='img',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='denker',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
