# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('framework', '0003_auto_20170410_1721'),
    ]
    
    state_operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.TextField(blank=True, max_length=250, null=True, unique=True)),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('sprache', models.TextField()),
                ('autor', models.TextField()),
                ('link', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'db_table': 'literatur_artikel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Buecher',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('sprache', models.TextField()),
                ('autor', models.TextField()),
                ('link', models.TextField()),
                ('quelle', models.TextField()),
            ],
            options={
                'db_table': 'literatur_buecher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dokumente',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('titel', models.TextField()),
                ('jahr', models.IntegerField()),
                ('text_de', models.TextField()),
                ('text_eng', models.TextField()),
                ('img', models.TextField()),
                ('denker', models.TextField()),
                ('orte', models.TextField()),
                ('link', models.TextField()),
            ],
            options={
                'db_table': 'literatur_dokumente',
                'managed': True,
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
