# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buecher',
            old_name='id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='dokumente',
            old_name='id',
            new_name='slug',
        ),
    ]
