# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0005_auto_20170410_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='slug',
        ),
        migrations.AddField(
            model_name='artikel',
            name='n',
            field=models.AutoField(default=9999999, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artikel',
            name='id',
            field=models.TextField(),
        ),
    ]
