# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0006_auto_20170413_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='id',
            new_name='slug',
        ),
    ]
