# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0010_auto_20170413_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='quelle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
