# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0012_auto_20170413_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumente',
            name='autor',
            field=models.TextField(default='nobnody'),
            preserve_default=False,
        ),
    ]
