# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0013_dokumente_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buecher',
            options={'managed': True, 'verbose_name': 'Buch', 'verbose_name_plural': 'Buecher'},
        ),
        migrations.AlterField(
            model_name='buecher',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buecher',
            name='quelle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buecher',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True),
        ),
    ]
