# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0014_auto_20170413_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buecher',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True),
        ),
    ]
