# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orte', '0002_auto_20170417_1252'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orte',
            table='orte',
        ),
    ]
