# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orte', '0006_auto_20170417_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orte',
            name='img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orte',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
