# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orte', '0012_auto_20170417_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orte',
            old_name='denker_neu',
            new_name='denker',
        ),
    ]
