# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verlag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verlagsprogramm',
            table='verlagsprogramm',
        ),
    ]
