# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verlag', '0006_auto_20170425_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verlagsprogramm',
            old_name='n',
            new_name='id',
        ),
    ]
