# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verlag', '0007_auto_20170425_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verlagsprogramm',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
