# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denker', '0003_delete_artikelalt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buecheralt',
        ),
        migrations.DeleteModel(
            name='DenkerAlt',
        ),
        migrations.DeleteModel(
            name='Ortebackup',
        ),
    ]
