# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denker', '0006_auto_20170403_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denker',
            old_name='n',
            new_name='id',
        ),
    ]
