# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denker', '0009_auto_20170403_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denker',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
