# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artikel',
            table='artikel',
        ),
        migrations.AlterModelTable(
            name='buecher',
            table='buecher',
        ),
        migrations.AlterModelTable(
            name='dokumente',
            table='dokumente',
        ),
        migrations.AlterModelTable(
            name='ereignisse',
            table='ereignisse',
        ),
        migrations.AlterModelTable(
            name='orte',
            table='orte',
        ),
        migrations.AlterModelTable(
            name='projekte',
            table='projekte',
        ),
        migrations.AlterModelTable(
            name='statischeinhalte',
            table='statische_inhalte',
        ),
        migrations.AlterModelTable(
            name='verlagsprogramm',
            table='verlagsprogramm',
        ),
        migrations.AlterModelTable(
            name='zitate',
            table='zitate',
        ),
    ]
