# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_auto_20170417_1246'),
    ]

    database_operations = [
        migrations.AlterModelTable('Verlagsprogramm', 'verlag_verlagsprogramm')
    ]

    state_operations = [
        migrations.DeleteModel('Verlagsprogramm')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
