# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossar',
            options={'verbose_name': 'Begriff', 'verbose_name_plural': 'Begriffe'},
        ),
        migrations.AlterField(
            model_name='glossar',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='begriff', unique=True),
        ),
    ]
