# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('framework', '0004_auto_20170417_1246'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Orte',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('name', models.TextField()),
                ('img', models.TextField()),
                ('text', models.TextField()),
                ('text_en', models.TextField()),
                ('lat', models.TextField()),
                ('lng', models.TextField()),
                ('denker', models.TextField()),
            ],
            options={
                'db_table': 'orte_orte',
                'managed': True,
            },
        ),
    ]
    
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
