# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orte', '0003_auto_20170417_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orte',
            old_name='id',
            new_name='slug',
        ),
    ]
