# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orte', '0007_auto_20170417_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orte',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orte',
            name='lng',
            field=models.FloatField(),
        ),
    ]
