# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('framework', '0006_auto_20170425_1135')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Projekte',
            fields=[
                ('n', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.TextField()),
                ('autor', models.TextField()),
                ('autor_id', models.TextField()),
                ('beschreibung', models.TextField()),
                ('spenden', models.IntegerField()),
                ('ziel', models.IntegerField()),
            ],
            options={
                'db_table': 'projekte_projekte',
                'managed': True,
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
