# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0002_auto_20170425_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projekte',
            old_name='n',
            new_name='id',
        ),
    ]
