# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denker', '0010_auto_20170414_1518'),
        ('projekte', '0003_auto_20170425_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekte',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='denker.Denker'),
        ),
    ]
