# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0004_projekte_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projekte',
            options={'managed': True, 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekte'},
        ),
        migrations.AddField(
            model_name='projekte',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projekte',
            name='autor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projekte',
            name='autor_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
