# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0005_auto_20170503_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stufen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoehe', models.IntegerField()),
                ('vorteile', models.TextField()),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projekte.Projekte')),
            ],
        ),
    ]
