# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0006_stufen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stufen',
            old_name='hoehe',
            new_name='betrag',
        ),
    ]
