# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0007_auto_20170607_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spenden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=100)),
                ('Nachname', models.CharField(max_length=100)),
                ('Betrag', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Validiert', models.BooleanField(default='False')),
            ],
        ),
    ]
