# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0008_spenden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spenden',
            name='Betrag',
        ),
        migrations.AddField(
            model_name='spenden',
            name='Stufe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projekte.Stufen'),
        ),
    ]
