# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekte', '0009_auto_20170616_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spenden',
            name='Stufe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projekte.Stufen'),
        ),
    ]
