# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0004_auto_20170410_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buecher',
            old_name='n',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dokumente',
            old_name='n',
            new_name='id',
        ),
    ]
