# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0009_auto_20170413_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'managed': True, 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True),
        ),
    ]
